name: stripe-report

on:
  schedule:
  - cron: 0 8 * * *
  workflow_dispatch: {}

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: ./scripts/install
    - name: Run
      env:
        TO_EMAIL: reports@dropseed.dev
        FROM_EMAIL: "Reports <reports@dropseed.dev>"
        SMTP_HOST: ${{ secrets.SMTP_HOST }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        STRIPE_KEY_pullapprove3: ${{ secrets.STRIPE_KEY_PULLAPPROVE3 }}
        STRIPE_KEY_pullapprove4: ${{ secrets.STRIPE_KEY_PULLAPPROVE4 }}
        STRIPE_KEY_deps3: ${{ secrets.STRIPE_KEY_DEPS3 }}
        STRIPE_KEY_boardbinder: ${{ secrets.STRIPE_KEY_BOARDBINDER }}
        STRIPE_KEY_forge: ${{ secrets.STRIPE_KEY_FORGE }}
      run: ./scripts/run
